### ISSUE TITLE
Nothing goes

### ISSUE THREAD

**Issue by AntDevPlus** [kharreMRC/Clonebit#1]
Hello partner.
I inform you that your code is not in adequacy with the MFC convention.
Indeed the acolades are not well placed.
```c#
// it's bad.
public void foo()
{
    //blabla
}


// it's good.
public void foo(){
    //blabla
}
```

See you soon.

**Comment by kharreMRC** [comment]
This convention sucks. You are wrong, it is the worst way to code.

**Comment by kharreMRC** [comment]
This convention sucks. You are wrong, it is the worst way to code.
